---
- hosts: all
  become: yes
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: vincent
        state: present
        key: "{{ lookup('file', '/home/ansibleadmin/.ssh/id_ed25519.pub') }}"
