---
- hosts: all
  become: true
  tasks:

  - name: Hacer el famoso apt update y upgrade en Ubuntu y Debian
    apt:
      update_cache: yes
      upgrade: yes
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name: Instalar apache en Ubuntu y Debian
    apt:
      name: apache2
      state: latest
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name: Iniciar el servicio Apache en Ubuntu y Debian
    ansible.builtin.service:
      name: apache2
      state: started
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name: Instalar apache en CentOS y RedHat
    yum:
      name: httpd
      state: latest
    when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

  - name: Iniciar el servicio Apache en CentOS y RedHat
    ansible.builtin.service:
      name: httpd
      state: started
    when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

  - name: Agregar usuario de la princesa mas bella
    ansible.builtin.user:
      name: anastasia
      shell: /bin/bash
      groups: sudo
      append: yes
    when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

  - name: Agregar usuario de la princesa mas bella
    ansible.builtin.user:
      name: anastasia
      shell: /bin/bash
      groups: wheel
      append: yes
    when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

  - name: Cambiar el titulo de la pagina web
    lineinfile:
      path: /var/www/html/index.html
      state: present
      regexp: '^NO JODA'
      line: 'LA PRINCESA ESTA RONCANDO'
      backrefs: yes

  - name: Copiar nueva super pagina web
    ansible.builtin.copy:
      src: /home/ansibleadmin/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'
